pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Create HelloWorld.java
        sh '''
        cat <<EOF>> HelloWorld.java
         public class HelloWorld {
            public static void main(String[] args) {
            System.ou.println("Hello, World");
            }
         }
         EOF
         '''
        // Compile and run
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        
 // Create Hello.js
        sh '''
        echo 'console.log("Hello, World");' > hello.js
        '''
        //Run
        sh 'node hello.js'
      }
    }
  }
}
